services:

  node:
    image: node:22
    container_name: learning-node
    working_dir: /app
    volumes:
      - ./app:/app
    command: node server.js
    ports:
      - "3000:3000"

  mysql:
    image: mysql:8.0
    container_name: learning-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: learning-phpmyadmin
    environment:
      PMA_HOST: learning-mysql
    ports:
      - "8083:80"